version: '3.8'

services:
  bancked-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bancked-app:latest
    restart: always
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_PASSWORD=1234
      - DB_DATABASE=font
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=font
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - /root/init:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p1234']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
