name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: List workspace contents
        run: |
          ls -la
          pwd

      - name: Build Docker images
        run: |
          echo "Starting Docker build..."
          docker compose build --no-cache
          echo "Build completed. Listing images..."
          docker images
          echo "Checking compose config..."
          docker compose config

      - name: Save Docker images
        run: |
          echo "Saving images to tar file..."
          docker save bancked-app:latest mysql:8.0 > images.tar
          ls -lh images.tar

      - name: Deploy to Server
        uses: appleboy/scp-action@v1.0.3
        with:
          host: 47.108.140.63
          username: root
          key: ${{ secrets.SERVER }}
          source: 'docker-compose.yml,init/,images.tar,Dockerfile,dist/,package*.json,pnpm-lock.yaml'
          target: '/root/bancked-project'
          strip_components: 0

      - name: Execute remote commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 47.108.140.63
          username: root
          key: ${{ secrets.SERVER }}
          script: |
            cd /root/bancked-project
            echo "Loading Docker images..."
            docker load < images.tar
            echo "Stopping existing containers..."
            docker compose down
            echo "Starting new containers..."
            docker compose up -d
            echo "Cleaning up..."
            rm images.tar
            docker image prune -f
            echo "Deployment completed. Checking container status..."
            docker compose ps
            docker compose logs --tail=50
