name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker compose build
          docker compose config
          docker images

      - name: Save Docker images
        run: |
          docker save bancked-app:latest mysql:8.0 > images.tar

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 47.108.140.63
          username: root
          key: ${{ secrets.SERVER }}
          source: 'docker-compose.yml,init/,images.tar,Dockerfile'
          target: '/root/bancked-project'
          strip_components: 0

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: 47.108.140.63
          username: root
          key: ${{ secrets.SERVER }}
          script: |
            cd /root/bancked-project
            docker load < images.tar
            docker compose down
            docker compose up -d
            rm images.tar
            docker image prune -f
